In [1]:
import numpy as np
import sys

### 1. Creating your first NumPy Array
We can create arrays using `np.array()` or functions like `np.arange()`. Let's create an array with 1,000,000 elements and compare its size to a standard Python list.

In [14]:
# Creating a list with 100000 integers
list_1000000 = list(range(1000000))

#Creat a numoy array of 1000000 integers
array_1000000 = np.arange(1000000)

#Print the size of the list and the array bytes
print (f"Size of Python list: {sys.getsizeof(list_1000000)} bytes")
print (f"size of array: {array_1000000.nbytes} bytes")

#time how long it takes to sum the list and the array
import time
#sum the list
start = time.time()
sum_list = sum(list_1000000)
end_time = time.time()
list_sum_time = (end_time - start) * 1000

#sum the array
start = time.time()
sum_array = np.sum(array_1000000)
end_time = time.time()
array_sum_time = (end_time - start) * 1000

#print the time taken to sum the list and the array
print (f"Time taken to sum the list: {list_sum_time:.2f} millisecounds")
print (f"Time taken to sum the array: {array_sum_time:.2f} millisecounds")


Size of Python list: 8000056 bytes
size of array: 8000000 bytes
Time taken to sum the list: 8.12 millisecounds
Time taken to sum the array: 0.92 millisecounds


### Quick Tip: Formatting Floats
When you use `:.2f`, you are rounding the display to 2 decimal places. You can change the number to show more or fewer decimals.

In [ ]:
pi_value = 3.1415926535

print(f"Original: {pi_value}")
print(f"Two decimals: {pi_value:.2f}")
print(f"Four decimals: {pi_value:.4f}")
print(f"Zero decimals: {pi_value:.0f}")

Original: 3.1415926535
Two decimals: 3.14
Four decimals: 3.1416
Zero decimals: 3


### 2. Vectorization
Another huge advantage is **vectorization**. In Python, to add 1 to every element in a list, you need a loop. In NumPy, you just add 1.

In [ ]:
# Adding 1 to every element
result_array = array_1000000 + 1

print("First 5 elements of original array:", array_1000000[:5])
print("First 5 elements after adding 1:", result_array[:5])

First 5 elements of original array: [0 1 2 3 4]
First 5 elements after adding 1: [1 2 3 4 5]


### 3. Multi-dimensional Arrays
In NumPy, dimensions are called **axes**. A 2D array is essentially a matrix. We can also check the `shape` (dimensions) and `dtype` (what kind of data is stored).

In [ ]:
# Creating a 2D array (3x3 matrix)
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

print("Matrix:\n", matrix)
print("Shape:", matrix.shape)
print("Data Type:", matrix.dtype)
print("Total elements:", matrix.size)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Data Type: int64
Total elements: 9


### 4. Useful Creation Functions
You don't always have to provide the data manually. NumPy has built-in functions for common patterns.

In [15]:
zeros = np.zeros((2, 3))    # 2x3 matrix of zeros
ones = np.ones((3, 2))     # 3x2 matrix of ones
identity = np.eye(3)       # 3x3 Identity matrix
random = np.random.random((2, 2)) # 2x2 matrix of random floats

print("Zeros:\n", zeros)
print ("Ones:\n", ones)
print("\nIdentity Matrix:\n", identity)
print("\nRandom Matrix:\n", random)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Matrix:
 [[0.48667231 0.95502787]
 [0.23721537 0.12776678]]


### 5. Indexing and Slicing
With 2D arrays, the syntax is `array[row, column]`. You can use `:` to select everything in a specific dimension.

In [18]:
# Accessing a single element (row 1, col 2 -> value 6)
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

print("Element at (1, 2):", matrix[1, 2])

# Accessing a whole row (the first row)
print("First row:", matrix[0, :])

# Accessing a whole column (the last column)
print("Last column:", matrix[:, -1])

# Slicing a sub-matrix (top-left 2x2)
print("Sub-matrix:\n", matrix[:2, :2])

Element at (1, 2): 6
First row: [1 2 3]
Last column: [3 6 9]
Sub-matrix:
 [[1 2]
 [4 5]]


### 6. Basic Statistics
NumPy also makes it very easy to calculate stats across the whole array or specific axes.

In [21]:
print("Sum of all elements:", matrix.sum())
print("Mean of all elements:", matrix.mean())
print("Max value in each column:", matrix.max(axis=0))
print("Sum of each row:", matrix.sum(axis=1))

Sum of all elements: 45
Mean of all elements: 5.0
Max value in each column: [7 8 9]
Sum of each row: [ 6 15 24]


### 5. Indexing and Slicing
With 2D arrays, the syntax is `array[row, column]`. You can use `:` to select everything in a specific dimension.

In [22]:
# Accessing a single element (row 1, col 2 -> value 6)
print("Element at (1, 2):", matrix[1, 2])

# Accessing a whole row (the first row)
print("First row:", matrix[0, :])

# Accessing a whole column (the last column)
print("Last column:", matrix[:, -1])

# Slicing a sub-matrix (top-left 2x2)
print("Sub-matrix:\n", matrix[:2, :2])

Element at (1, 2): 6
First row: [1 2 3]
Last column: [3 6 9]
Sub-matrix:
 [[1 2]
 [4 5]]


### 6. Basic Statistics
NumPy also makes it very easy to calculate stats across the whole array or specific axes.

In [ ]:
print("Sum of all elements:", matrix.sum())
print("Mean of all elements:", matrix.mean())
print("Max value in each column:", matrix.max(axis=0))
print("Sum of each row:", matrix.sum(axis=1))

### 7.Arthemetic operations
we can able to use numpy for operations like +, -, /, *, ....

In [27]:

a = np.array([[1,2,3],[4,5,6]])
             
b = np.array([[4,5,6],[8,9,10]])

In [25]:
print (a+b)

[[ 5  7  9]
 [12 14 16]]


In [28]:
print (a/b)

[[0.25       0.4        0.5       ]
 [0.5        0.55555556 0.6       ]]


In [29]:
print (a*b)

[[ 4 10 18]
 [32 45 60]]


In [30]:
print (a-b)

[[-3 -3 -3]
 [-4 -4 -4]]


In [ ]:
print (b//a) # it wiil give int values

[4 2 2]


In [ ]:
print (b%a)

[0 1 0]


In [31]:
print (a**2) # powers

[[ 1  4  9]
 [16 25 36]]


### 8. Universal function -> ufuncs

In [ ]:
arr = np.array ([1,4,9,16])

In [ ]:
print (np.sqrt(arr))

[1. 2. 3. 4.]


In [ ]:
print (np.exp([1,2]))

[2.71828183 7.3890561 ]


In [39]:
angles = np.array ([90, np.pi/2, np.pi]) # sine function -> np.sin
print (np.cos(angles))

[-4.48073616e-01  6.12323400e-17 -1.00000000e+00]


### 9. Indexing and Slicing


In [ ]:
a = [1,2,3,4,5]

In [ ]:
a[: : 2]

[1, 3, 5]

In [ ]:
a[-1:-4: -1]

[5, 4, 3]

In [ ]:
arr = np.array([10,20,30,40,50])

In [ ]:
arr[: : 2]

array([10, 30, 50])

In [ ]:
print (arr[-1])

50


In [ ]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [ ]:
print (matrix[0:2, :])
# first we have to give the no of row and after comma we have to give the column index
# : will give the complete thing in the array or line or any thing that is present

[[1 2 3]
 [4 5 6]]


In [ ]:
print (matrix[1: , 1: ])

[[5 6]
 [8 9]]


In [ ]:
#np.take  -> built in function to perform indexing and slicing
arr = np.array([10,20,30,40,50])
ind = [0,2]
print(np.take(arr, ind))

[10 30]


In [ ]:
#iterating with the nditer()


In [41]:
arr = np.array([[1,2],[3,4]])

In [46]:
import time

for  x in np.nditer(arr):
  print (x, end = " ")

  #time.sleep(2)

1 2 3 4 

In [47]:
#ndenumerate()-> both index + value

arr = [1,2,3,4,5]
for ind, x in np.ndenumerate(arr):
  print (ind, x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


In [ ]:
# views vs copies
arr = np.array ([1,2,3,4,5])
view = arr[1:3]
view

array([2, 3])

In [ ]:
view [0] = 200
view


array([200,   3])

In [ ]:
arr


array([  1, 200,   3,   4,   5])

In [ ]:
copy = arr[1:3].copy()
copy


array([200,   3])

In [ ]:
copy [0] = 2
copy

array([2, 3])

In [ ]:
arr

array([  1, 200,   3,   4,   5])

### Transpose of matrix


In [ ]:
arr = np.array([[1,2],[3,4]])
arr
print (arr.transpose())


[[1 3]
 [2 4]]


In [ ]:
#swapaxes -> we swap 2 specific axis of array matrix

In [ ]:
arr = np.array ([[[1,2],[3,4]]])
arr

array([[[1, 2],
        [3, 4]]])

In [53]:
swap = np.swapaxes(arr, 0, 1)
swap.shape

AxisError: axis2: axis 1 is out of bounds for array of dimension 1

In [ ]:
#concatinations
a = np.array ([1,2])
b = np.array ([3,4])


In [ ]:
combine = np.concatenate((a,b))
combine


array([1, 2, 3, 4])

In [ ]:
#Vertical stack -> vstack
arr1 = np.array ([[1,2],[3,4]])
arr2 = np.array ([[5,6],[7,8]])
print (np.vstack((arr1, arr2)))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#hstack
print (np.hstack((arr1,arr2)))

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#stack ((a,b), axis)
print (np.stack((arr1,arr2), axis = 0))
print ("-------------------------------------------")
print (np.stack((arr1,arr2), axis = 1))


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
-------------------------------------------
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [ ]:
#splitting the array

In [ ]:
arr = np.array ([[1,2],[3,4],[5,6],[7,8]])
print (np.split(arr, 4))
print ("------------------------------")
print (np.hsplit(arr, 2))
print ("------------------------------")
print (np.vsplit(arr, 2))

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]
------------------------------
[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]
------------------------------
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [ ]:
#repeating

In [ ]:
arr = np.array ([1,2,3])
print (np.repeat(arr,2))

[1 1 2 2 3 3]


In [ ]:
#tile -> it will repeate my whole array
print (np.tile(arr,2))

[1 2 3 1 2 3]


In [ ]:
#aggrigate functions
arr = np.array ([1,2,3])
print (np.sum(arr))
print ("---------------------")
print (np.mean(arr))
print ("---------------------")
print (np.median(arr))
print ("---------------------")
print (np.average(arr))
print ("---------------------")
print (np.std(arr))
print ("---------------------")
print (np.var(arr))
print ("---------------------")
print (np.min(arr))
print ("---------------------")
print (np.max(arr))
print ("---------------------")
print (np.argmin(arr))
print ("---------------------")
print (np.argmax(arr))

6
---------------------
2.0
---------------------
2.0
---------------------
2.0
---------------------
0.816496580927726
---------------------
0.6666666666666666
---------------------
1
---------------------
3
---------------------
0
---------------------
2


In [ ]:
#cumulative Operations -> running total
print (np.cumsum(arr))
print ("---------------------")
print (np.cumprod(arr))

[1 3 6]
---------------------
[1 2 6]


In [ ]:
#where
result = np.where (arr <2, "low","High")
result


array(['low', 'High', 'High'], dtype='<U4')

In [ ]:
#argwhere -> it will give the index where the comdition is satisfied
print (np.argwhere(arr>2))

[[2]]


In [ ]:
#logical gates
arr = np.array([10,20,30,40,50,60])
mask = np.logical_and(arr>10, arr<50)
print (mask)

[False  True  True  True False False]


In [ ]:
print (matrix)
print ("-------------------------------")
print (np.argwhere(matrix >5))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-------------------------------
[[1 2]
 [2 0]
 [2 1]
 [2 2]]


In [ ]:
print (arr)
# print ("-----------------------------")
# print (np.logical_and(arr > 13, arr< 60)) # this will give true or false
# print ("-----------------------------")
# mask = np.logical_and(arr > 13, arr< 60)# mask is the boolean where it will give true and false
# arr[mask] # this will display or fetch the values in it
print ("-----------------------------")
print (np.logical_or(arr > 13, arr< 60))
print ("---------------------------------------------")
mask = np.logical_or(arr > 13, arr< 60)
arr[mask]



[10 20 30 40 50 60]
-----------------------------
[ True  True  True  True  True  True]
---------------------------------------------


array([10, 20, 30, 40, 50, 60])

In [ ]:
print (arr)
a = np.take(arr, 1) # take will be displaying thet given index
print (a)

[10 20 30 40 50 60]
20


In [ ]:
arr1 = np.array([0,1,2,3,0,4,5])
print (np.nonzero(arr1)) # this eill remove zeros in the array

(array([1, 2, 3, 5, 6]),)


### Broadcasting (imp topic)
what it means ?
it will streach the shape of the array to match the shape of the other array

# Numpy compares the shape of the arrays from the end (right to left ) and follows these rules:

rule :


*   if the shapes are equal they are compatible
*   if one is 1, it can be strached to match the other
* if the shapes are different and 1 or not equal -> error






In [ ]:
image = np.array ([[200,150],[100,250]])
image



(2, 2)

In [ ]:
brightness = image +50
brightness


array([[250, 200],
       [150, 300]])

#Vectorization:

In [ ]:
#np.vectorize() -> convert a regular function to be applied on an array.
def square(x):
  return x*x
vfunc = np.vectorize(square)

In [ ]:
arr

array([10, 20, 30, 40, 50, 60])

In [ ]:
print (vfunc(arr))

[ 100  400  900 1600 2500 3600]


# Dealing with missing values
###house price prediction model
###local | no of rooms | bath rooms
### -there will be some missing valuse in ur list so numpy will deal with the missing values


In [ ]:
#np.nan -> not a number
a = np.array ([1, 2, np.nan, 4])
a

array([ 1.,  2., nan,  4.])

In [ ]:
#np.inf and -np.inf -> these will represent positive negative values

In [ ]:
#np.isnan
#np.isinf
#np.isinfinite

# --> these are the functions used to detect any null values infinate or finite value

In [ ]:
print (np.isnan(a))

[False False  True False]


In [ ]:
b = np.array ([1, np.nan, np.inf, 10.2, 40])
print (np.isinf(b))
print (np.logical_or(np.isinf(b),np.isnan(b)))

[False False  True False False]
[False  True  True False False]


In [ ]:
#replace or remove the values

In [ ]:
#np.nan_to_num()
new_b = np.nan_to_num(b)
print (new_b)
print ("-----------------------------------x")
new_b1 = np.nan_to_num(b, nan = 0, posinf = 100, neginf = -100)
new_b1

[1.00000000e+000 0.00000000e+000 1.79769313e+308 1.02000000e+001
 4.00000000e+001]
-----------------------------------


array([  1. ,   0. , 100. ,  10.2,  40. ])

# Exercise 1 (Basic): E-Commerce Revenue & Discount Calculation
Business Problem: An online store wants to compute total net revenue for 5 products after applying a flat 10% promotional discount across all items.

### NumPy Concept Used: Basic array element-wise arithmetic and summation.

In [4]:
prices = np.array([100, 250, 400, 50, 120])       # Price per unit in USD
quantities = np.array([2, 1, 3, 10, 5])            # Units sold
discount_rate = 0.10                              # 10% discount


gross_revenue = prices * quantities   # Calculate gross revenue per product


net_revenue = gross_revenue * (1 - discount_rate)   # Apply discount vectorially

print ("Gross Revenue per Product:", gross_revenue)
print("Net Revenue per Product:", net_revenue)
print(f"Total Sales Revenue: ${np.sum(net_revenue):,.2f}")

Gross Revenue per Product: [ 200  250 1200  500  600]
Net Revenue per Product: [ 180.  225. 1080.  450.  540.]
Total Sales Revenue: $2,475.00


# Exercise 2 (Basic): Retail Multi-Store Inventory Tracking

Business Problem: A retail chain has 3 store locations and sells 4 product types. Management needs to know total stock per product across all stores, and total stock held in each store.

### NumPy Concept Used: 2D arrays (matrices) and axis-wise reductions (axis=0 vs axis=1).

In [3]:
# Rows = Stores (Store 1, Store 2, Store 3)
# Columns = Products (Laptops, Phones, Tablets, Headphones)
inventory = np.array([
    [10, 15, 20, 5],   # Store 1
    [5,   0, 12, 30],  # Store 2
    [25, 10,  5, 15]   # Store 3
])

# Sum across rows (axis=0) to get total units per product type
total_per_product = np.sum(inventory, axis=0)

# Sum across columns (axis=1) to get total units inside each store
total_per_store = np.sum(inventory, axis=1)

print("Total stock per product:", total_per_product)
print("Total stock in each store:", total_per_store)

Total stock per product: [40 25 37 50]
Total stock in each store: [50 47 55]


# Exercise 3 (Intermediate): Foreign Currency Conversion

Business Problem: A multinational company records daily sales across 3 foreign branches in Euros (EUR), British Pounds (GBP), and Japanese Yen (JPY). Convert all transaction amounts into USD.

### NumPy Concept Used: Broadcasting (matching a 2D matrix with a 1D vector).

In [5]:
# Daily sales records (Rows = Days 1 to 4; Columns = EUR, GBP, JPY)
sales_foreign = np.array([
    [1000, 800,  150000],
    [1200, 850,  180000],
    [900,  700,  120000],
    [1100, 950,  160000]
])

# Exchange rates to USD: [1 EUR = 1.08 USD, 1 GBP = 1.27 USD, 1 JPY = 0.0067 USD]
usd_rates = np.array([1.08, 1.27, 0.0067])

# NumPy automatically stretches usd_rates across all rows
sales_usd = sales_foreign * usd_rates

print("Daily Sales in USD:\n", np.round(sales_usd, 2))

Daily Sales in USD:
 [[1080.  1016.  1005. ]
 [1296.  1079.5 1206. ]
 [ 972.   889.   804. ]
 [1188.  1206.5 1072. ]]


# Exercise 4 (Intermediate): HR Payroll & Performance Bonuses
Business Problem: HR needs to compute employee final payouts. Employees with a performance rating of 4.0 or higher receive a 10% bonus; all others receive a standard 2% bonus.

### NumPy Concept Used: Conditional logic with np.where().

In [7]:
salaries = np.array([50000, 60000, 55000, 70000, 65000])  # Base salaries
ratings = np.array([4.5, 3.8, 4.2, 4.0, 3.5])          # Performance ratings

bonous_percentages = np.where(ratings >= 4.0, 0.10, 0.02)  # 10% bonus for ratings >= 4.0, else 2%

bonuses = salaries * bonous_percentages
final_payouts = salaries + bonuses

print("Base Salaries:", salaries)
print("Performance Ratings:", ratings)
print("Bonus Percentages:", bonous_percentages)
print("Bonuses:", bonuses)
print("Final Payouts:", final_payouts)
print (f"Total Payroll Cost: ${np.sum(final_payouts):,.2f}")

Base Salaries: [50000 60000 55000 70000 65000]
Performance Ratings: [4.5 3.8 4.2 4.  3.5]
Bonus Percentages: [0.1  0.02 0.1  0.1  0.02]
Bonuses: [5000. 1200. 5500. 7000. 1300.]
Final Payouts: [55000. 61200. 60500. 77000. 66300.]
Total Payroll Cost: $320,000.00


# Exercise 5 (Intermediate): Warehouse Temperature Sensor Data Hygiene
Business Problem: Cold-storage sensors periodically experience network drops and record NaN (missing values). Calculate the average temperature without error, and impute (fill) missing values with the average temperature.

### NumPy Concept Used: np.isnan(), np.nanmean(), and np.nan_to_num().

In [8]:
readings = np.array ([2.1, 3.3, np.nan, 4.5, np.nan, 5.0])
#calculate the average temperature ignoring NaN values
valid_mean = np.nanmean(readings)

#impute missing NaN values with the calculated mean
cleaned_readings = np.nan_to_num(readings, nan=valid_mean)

print("Original Readings:", readings)
print("Average Temperature (ignoring NaN):", valid_mean)
print (f"calculated mean: {valid_mean:.2f}°C")
print("cleaned Dataset: ", np.round(cleaned_readings, 2))

Original Readings: [2.1 3.3 nan 4.5 nan 5. ]
Average Temperature (ignoring NaN): 3.725
calculated mean: 3.73°C
cleaned Dataset:  [2.1  3.3  3.72 4.5  3.72 5.  ]


# Exercise 6 (Intermediate): Marketing Campaign Performance & Outlier Detection
Business Problem: A marketing team wants to compare daily user conversions between Campaign A and Campaign B, find average performance, and identify the single best day for Campaign B.

### NumPy Concept Used: Statistical functions (mean, std, argmax).

In [9]:
campaign_a = np.array([12, 15, 9, 18, 22, 14, 11])
campaign_b = np.array([25, 28, 19, 31, 24, 29, 27])

print (f"Campaign A - Mean: {np.mean(campaign_a):.1f}, Std Dev: {np.std(campaign_a):.1f}")
print (f"Campaign B - Mean: {np.mean(campaign_b):.1f}, Std Dev: {np.std(campaign_b):.1f}")

best_day_b = np.argmax(campaign_b)
print (f"Campaign B hit peak conversion ({campaign_b[best_day_b]})on Day {best_day_b + 1}")

Campaign A - Mean: 14.4, Std Dev: 4.1
Campaign B - Mean: 26.1, Std Dev: 3.6
Campaign B hit peak conversion (31)on Day 4


# Exercise 7 (Advanced): Manufacturing Raw Material Cost Analysis
Business Problem: A factory produces 3 distinct finished goods using 4 raw components. Given the bill-of-materials matrix and raw component costs, calculate the total raw material cost to produce 1 unit of each product.

### NumPy Concept Used: Matrix Multiplication (@ operator or np.matmul).

In [10]:
# Rows = Finished Products (Product X, Product Y, Product Z)
# Columns = Units of Material needed (Steel, Plastic, Rubber, Glass)
bill_of_materials = np.array([
    [2, 1, 0, 4],  # Product X
    [1, 3, 2, 1],  # Product Y
    [0, 2, 5, 3]   # Product Z
])

#unit cost per material in USD: [Steel: $10, Plastic: $5, Rubber: $12, Glass: $3]
unit_costs = np.array([10, 5, 12, 3])

cost_per_product = bill_of_materials @ unit_costs  # Matrix multiplication to get total cost per product
print("Total Raw Material Cost per Product:", cost_per_product)
print (" Raw Material Cost for Product X: $", cost_per_product[0])
print (" Raw Material Cost for Product Y: $", cost_per_product[1])
print (" Raw Material Cost for Product Z: $", cost_per_product[2])


Total Raw Material Cost per Product: [37 52 79]
 Raw Material Cost for Product X: $ 37
 Raw Material Cost for Product Y: $ 52
 Raw Material Cost for Product Z: $ 79


# Exercise 8 (Advanced): Machine Learning Data Feature Scaling (Min-Max Normalization)
Business Problem: Real estate data contains features on completely different numerical scales (Prices in hundreds of thousands, Square Footage in thousands, Bedrooms in single digits). Normalize all numerical features into a range between 0 and 1 so machine learning algorithms can process them fairly.

### NumPy Concept Used: Min-Max scaling formula implementation via array broadcasting:

$$X_{norm} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

In [11]:
# Matrix: [Price ($k), Area (sqft), Bedrooms]
housing_data = np.array([
    [300, 1500, 3],
    [500, 2500, 4],
    [150,  800, 2],
    [800, 3500, 5]
])

# Minimum and Maximum along columns (axis=0)
col_min = housing_data.min(axis=0)
col_max = housing_data.max(axis=0)

# Vectorized Min-Max Scaling
normalized_housing = (housing_data - col_min) / (col_max - col_min)

print("Normalized Housing Features (Range 0 to 1):\n", np.round(normalized_housing, 3))

Normalized Housing Features (Range 0 to 1):
 [[0.231 0.259 0.333]
 [0.538 0.63  0.667]
 [0.    0.    0.   ]
 [1.    1.    1.   ]]


# Exercise 9 (High-End): Financial Portfolio Expected Return & Volatility Risk
Business Problem: An asset management firm holds a portfolio of 3 stocks with specific portfolio weight allocations. Given daily percentage returns over a week, compute total daily portfolio returns and the overall volatility (risk).

### NumPy Concept Used: Dot products (np.dot), matrix multiplication, and standard deviation calculations.

In [12]:
# Portfolio Weights (40% Stock A, 30% Stock B, 30% Stock C)
weights = np.array([0.4, 0.3, 0.3])

# Daily % returns over 5 trading days for [Stock A, Stock B, Stock C]
daily_stock_returns = np.array([
    [ 0.010, -0.005,  0.020],  # Day 1
    [ 0.005,  0.010,  0.015],  # Day 2
    [-0.010,  0.002, -0.010],  # Day 3
    [ 0.020,  0.015,  0.030],  # Day 4
    [ 0.001, -0.001,  0.005]   # Day 5
])

# Portfolio daily returns = Daily Returns Matrix multiplied by Weight Vector
portfolio_daily_returns = daily_stock_returns @ weights

# Daily Portfolio Risk (Standard Deviation)
portfolio_volatility = np.std(portfolio_daily_returns)

print("Daily Portfolio Returns:", np.round(portfolio_daily_returns, 4))
print(f"Overall Portfolio Daily Risk (Volatility): {portfolio_volatility:.4%}")

Daily Portfolio Returns: [ 0.0085  0.0095 -0.0064  0.0215  0.0016]
Overall Portfolio Daily Risk (Volatility): 0.9246%


# Exercise 10 (High-End): Recommender Systems - Cosine Similarity Scoring
Business Problem: A streaming platform wants to measure how similar two users' viewing habits are based on their ratings for 4 movie genres (Action, Comedy, Drama, Sci-Fi) to decide whether to recommend similar movies.

### NumPy Concept Used: Vector Norms (np.linalg.norm) and Cosine Similarity:
$$\cos(\theta) = \frac{A \cdot B}{\Vert{}A\Vert{} \Vert{}B\Vert{}}$$

In [2]:
# Genre Ratings (1 to 5 scale): [Action, Comedy, Drama, Sci-Fi]
user_alex = np.array([5, 1, 4, 0])
user_sam  = np.array([4, 2, 5, 1])

# Step 1: Dot product of vectors
dot_product = np.dot(user_alex, user_sam)

# Step 2: Magnitude (Euclidean norm) of each vector
norm_alex = np.linalg.norm(user_alex)
norm_sam = np.linalg.norm(user_sam)

# Step 3: Compute Cosine Similarity
similarity = dot_product / (norm_alex * norm_sam)

print(f"Alex Vector Magnitude: {norm_alex:.2f}")
print(f"Sam Vector Magnitude: {norm_sam:.2f}")
print(f"User Preference Similarity Score: {similarity:.4f} (Scale: -1 to 1)")

Alex Vector Magnitude: 6.48
Sam Vector Magnitude: 6.78
User Preference Similarity Score: 0.9555 (Scale: -1 to 1)
