# Case study: Dimensionality Reduction using PCA for Breast Cancer Classification 🏥

### 🏢 Business Problem Context

The Breast Cancer dataset has 30 features (e.g., radius, texture, smoothness of cell nuclei).

Many of these features are correlated and redundant.

Training directly on all 30 features may increase computation and risk of overfitting.

PCA helps reduce to 10 principal components while retaining most of the information.

Then, we use Logistic Regression on these 10 components to classify tumors as benign or malignant.

In [1]:
from sklearn.datasets import load_breast_cancer

from sklearn.decomposition import PCA

from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import train_test_split

from sklearn.pipeline import Pipeline

import numpy as np

In [2]:
# Step 1: Load dataset

data = load_breast_cancer() # in built dataset for learning purpose in sklearn.datasets
X, y = data.data, data.target
# Breast Cancer dataset: 569 samples, 30 features, binary target (0=malignant, 1=benign)


In [4]:
X[: 5]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
        1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
        4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
        2.250e-02, 4.571e-03, 2.357e

In [3]:
# Step 2: Train/test split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y)
# Stratified split ensures same class proportion in train and test sets

X_train.shape,X_test.shape

((398, 30), (171, 30))

In [5]:
# view top 5 records
X_train[:-5]

array([[1.162e+01, 1.818e+01, 7.638e+01, ..., 1.416e-01, 2.660e-01,
        9.270e-02],
       [1.120e+01, 2.937e+01, 7.067e+01, ..., 0.000e+00, 1.566e-01,
        5.905e-02],
       [1.057e+01, 1.832e+01, 6.682e+01, ..., 2.222e-02, 2.699e-01,
        6.736e-02],
       ...,
       [1.108e+01, 1.471e+01, 7.021e+01, ..., 4.306e-02, 1.902e-01,
        7.313e-02],
       [2.059e+01, 2.124e+01, 1.378e+02, ..., 2.113e-01, 2.480e-01,
        8.999e-02],
       [1.944e+01, 1.882e+01, 1.281e+02, ..., 2.060e-01, 3.266e-01,
        9.009e-02]], shape=(393, 30))

In [7]:
y_train[:5]

array([1, 1, 1, 1, 1])

In [8]:
# Step 3: Define pipeline (chaining steps together)
pipe = Pipeline([
    ("scaler", StandardScaler()),         # Standardize features (mean=0, variance=1)
    ("pca", PCA(n_components=10)),        # Reduce 30 features → 10 principal components
    ("clf", LogisticRegression(max_iter=500))  # Logistic Regression classifier
])


In [9]:

# Step 4: Train pipeline (all steps applied in correct order within CV folds)
pipe.fit(X_train, y_train)

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators <combining_estimators>` for more details.","[('scaler', ...), ('pca', ...), ...]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing <metadata_routing>`.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
Name,Type,Value
"classes_ classes_: ndarray of shape (n_classes,)The classes labels. Only exist if the last step of the pipeline is aclassifier.","ndarray[int64](2,)","[0,1]"
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`. Only defined if theunderlying first estimator in `steps` exposes such an attributewhen fit... versionadded:: 0.24,int,30
,"copy copy: bool, default=TrueIf False, try to avoid a copy and do inplace scaling instead.This is not guaranteed to always work inplace; e.g. if the data isnot a NumPy array or scipy.sparse CSR matrix, a copy may still bereturned.",True
,"with_mean with_mean: bool, default=TrueIf True, center the data before scaling.This does not work (and will raise an exception) when attempted onsparse matrices, because centering them entails building a densematrix which in common use cases is likely to be too large to fit inmemory.",True
,"with_std with_std: bool, default=TrueIf True, scale the data to unit variance (or equivalently,unit standard deviation).",True
Name,Type,Value


In [10]:
# Step 5: Evaluate model performance
print("Test Accuracy with PCA:", pipe.score(X_test, y_test))
# Measures classification accuracy using reduced features

Test Accuracy with PCA: 0.9707602339181286


In [11]:
# Step 6: Check how much variance is retained by 10 components

pca_model = pipe.named_steps["pca"]

print("Explained Variance (10 comps):", np.sum(pca_model.explained_variance_ratio_))

# Shows % of information preserved after dimensionality reduction


Explained Variance (10 comps): 0.9561577528297448


### Observation

By reducing 30 features to just 10 principal components, we still retained about 95% of the original variance.

The Logistic Regression model achieved ~96% accuracy on the test set, which is almost as good as using all features.

This shows how PCA helps simplify high-dimensional datasets without losing much predictive power — improving efficiency and interpretability.