# Assignment 1 - Working with NumPy

**Objective:** Understand the basics of NumPy, array creation, and manipulation.

## Step 1: Import NumPy
First, we import the NumPy library to use its array manipulation and mathematical functions.

In [1]:
import numpy as np

## Part 1: 1D Array Operations
Create a 1D NumPy array with integers from 1 to 20. Calculate statistical metrics and find indices of elements greater than 10.

In [2]:
# Create a 1D array with integers from 1 to 20
arr_1d = np.arange(1, 21)
print("1D Array:", arr_1d)

# a. Calculate the sum, mean, median, and standard deviation
arr_sum = np.sum(arr_1d)
arr_mean = np.mean(arr_1d)
arr_median = np.median(arr_1d)
arr_std = np.std(arr_1d)

print(f"Sum: {arr_sum}")
print(f"Mean: {arr_mean}")
print(f"Median: {arr_median}")
print(f"Standard Deviation: {arr_std:.2f}")

# b. Find the indices of elements greater than 10 in the array
indices_gt_10 = np.where(arr_1d > 10)
print("Indices where elements > 10:", indices_gt_10[0])

1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.77
Indices where elements > 10: [10 11 12 13 14 15 16 17 18 19]


## Part 2: 2D Array Operations
Create a 2D NumPy array of shape 4x4 with numbers ranging from 1 to 16. Print it, find its transpose, and calculate row-wise and column-wise sums.

In [3]:
# Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16
arr_2d = np.arange(1, 17).reshape(4, 4)

# a. Print the array
print("2D Array (4x4):\n", arr_2d)

# b. Find the transpose of the array
arr_transpose = arr_2d.T
print("\nTranspose of the Array:\n", arr_transpose)

# c. Calculate the row-wise and column-wise sums of the array
row_sums = np.sum(arr_2d, axis=1)
col_sums = np.sum(arr_2d, axis=0)
print("\nRow-wise Sums:", row_sums)
print("Column-wise Sums:", col_sums)

2D Array (4x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transpose of the Array:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Row-wise Sums: [10 26 42 58]
Column-wise Sums: [28 32 36 40]


## Part 3: Random Arrays & Matrix Operations
Create two 3x3 arrays filled with random integers between 1 and 20. Perform element-wise operations and compute their dot product.

In [4]:
# Create two 3 X 3 arrays filled with random integers between 1 and 20
rand_arr1 = np.random.randint(1, 21, size=(3, 3))
rand_arr2 = np.random.randint(1, 21, size=(3, 3))

print("Random Array 1:\n", rand_arr1)
print("\nRandom Array 2:\n", rand_arr2)

# a. Perform element-wise addition, subtraction, and multiplication
print("\nElement-wise Addition:\n", rand_arr1 + rand_arr2)
print("\nElement-wise Subtraction:\n", rand_arr1 - rand_arr2)
print("\nElement-wise Multiplication:\n", rand_arr1 * rand_arr2)

# b. Compute the dot product of the two arrays
dot_product = np.dot(rand_arr1, rand_arr2)
print("\nDot Product:\n", dot_product)

Random Array 1:
 [[13 13 19]
 [ 4  7  4]
 [ 8 17 10]]

Random Array 2:
 [[20  8 11]
 [ 2  2 19]
 [18  1  3]]

Element-wise Addition:
 [[33 21 30]
 [ 6  9 23]
 [26 18 13]]

Element-wise Subtraction:
 [[ -7   5   8]
 [  2   5 -15]
 [-10  16   7]]

Element-wise Multiplication:
 [[260 104 209]
 [  8  14  76]
 [144  17  30]]

Dot Product:
 [[628 149 447]
 [166  50 189]
 [374 108 441]]


## Part 4: Reshaping and Slicing
Reshape a 1D array of size 12 into a 3x4 2D array and slice the first two rows and last two columns.

In [5]:
# Reshape a 1D array of size 12 into a 3 X 4 2D array
arr_12 = np.arange(12)
arr_3x4 = arr_12.reshape(3, 4)
print("Reshaped 3x4 Array:\n", arr_3x4)

# Slice the first two rows and last two columns
sliced_arr = arr_3x4[:2, -2:]
print("\nSliced Array (First 2 rows, Last 2 columns):\n", sliced_arr)

Reshaped 3x4 Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Sliced Array (First 2 rows, Last 2 columns):
 [[2 3]
 [6 7]]
